#!/usr/bin/env python

Import("env")
Import("env_modules")

js_pre = [
    "#modules/webxr/native/webxr.js",
]
for js in js_pre:
    env.Append(LINKFLAGS=["--pre-js", env.File(js).path])
build_targets = ["#bin/godot${PROGSUFFIX}.js", "#bin/godot${PROGSUFFIX}.wasm"]
if env["threads_enabled"]:
    build_targets.append("#bin/godot${PROGSUFFIX}.worker.js")
env.Depends(build_targets, js_pre)

env_webxr = env_modules.Clone()

env_webxr.add_source_files(env.modules_sources, "*.cpp")
